name: alexandria

services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    ports:
      - "8096:8096/tcp"
      - "7359:7359/udp"
    volumes:
      - '${root:?}/Jellyfin/config:/config'
      - '${root:?}/Jellyfin/cache:/cache'
      - '${root:?}/Sync/Media:/media'
